# Generated by Django 5.0.1 on 2024-01-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="type",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="wine",
            name="year",
            field=models.CharField(max_length=20),
        ),
    ]
