# Generated by Django 5.0.1 on 2024-01-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0002_wine_type_alter_wine_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="notes",
            field=models.TextField(max_length=1000),
        ),
    ]
