# Generated by Django 5.0.1 on 2024-01-26 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0004_alter_wine_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="description",
                to="wines.wine",
            ),
        ),
    ]
