# Generated by Django 4.1.2 on 2024-04-10 04:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_restaurant_state_restaurant_zip_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="owner",
        ),
    ]
